/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.LibrarianPanel;

import Business.Branch;
import Business.Business;
import Library.RentalRequest;
import Material.Book;
import Material.Magazine;
import Role.Role;
import UI.MainJFrame;
import UserAccount.UserAccount;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 15512
 */
public class LibrarianJFrame extends javax.swing.JFrame {

    private Business business;
    private Branch branch;
    private UserAccount useraccount;
    DefaultTableModel matTable;
    DefaultTableModel rrTable;
    /**
     * Creates new form SystemAdminJFrame
     */
    public LibrarianJFrame(Business business, Branch branch, UserAccount useraccount) {
        initComponents();
        this.setVisible(true);
        this.branch = branch;
        this.business = business;
        this.useraccount = useraccount;
        branchName.setText(branch.getName());
        librarianName.setText(branch.getLibrary().getLibrarian().getEmp_name());
        expLib.setText(String.valueOf(branch.getLibrary().getLibrarian().getExp()));
        this.matTable = (DefaultTableModel) materialsTable.getModel();
        this.rrTable = (DefaultTableModel) rentalsTable.getModel();
        populateMaterial();
        populateRR();
        populateAG();
    }

    public void populateRR() {
        rrTable.setRowCount(0);
        ArrayList<RentalRequest> rrs = this.branch.getLibrary().getRentalRequests().getRentalRequests();
        System.out.println("size - "+rrs.size());
        if (rrs.size() > 0) {
            for (RentalRequest rr : rrs) {
                Object[] row = new Object[6];
                row[0] = rr.getId();
                row[1] = rr.getPrice();
                row[2] = rr.getMaterial().getName();
                row[3] = rr.getDuration();
                row[4] = rr.getStatus();
                row[5] = rr.getCusId();
                rrTable.addRow(row);
            }
        }
    }
    
    public void populateAG() {
        authors.removeAllItems();
        genres.removeAllItems();
        for (String a : this.branch.getLibrary().getAuthorDirectory()) {
            authors.addItem(a);
        }
        for (String g : this.branch.getLibrary().getGenreDirectory()) {
            genres.addItem(g);
        }
    }
    
    public void populateMaterial() {
        matTable.setRowCount(0);

        ArrayList<Book> books = this.branch.getLibrary().getBookDirectory().getBooks();
        ArrayList<Magazine> mags = this.branch.getLibrary().getMagDiretory().getMagazines();

        if (books.size() > 0) {
            for (Book b : books) {
                Object[] row = new Object[10];
                row[0] = b.getId();
                row[1] = b.getMaterialType();
                row[2] = b.getName();
                row[3] = b.getAuthor();
                row[4] = b.getGenre();
                row[5] = b.getPages();
                row[6] = "-";
                row[7] = "-";
                row[8] = b.getIsAvailable()?"YES":"NO";
                row[9] = b.getRegisteredDate();
                matTable.addRow(row);
            }
        }

        if (mags.size() > 0) {
            for (Magazine m: mags) {
                Object[] row = new Object[10];
                row[0] = m.getId();
                row[1] = m.getMaterialType();
                row[2] = "-";
                row[3] = "-";
                row[4] = "-";
                row[5] = "-";
                row[6] = m.getCompany();
                row[7] = m.getIssueType();
                row[8] = m.getIsAvailable()?"YES":"NO";
                row[9] = m.getRegisteredDate();
                matTable.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        backBtn1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        materialsTable = new javax.swing.JTable();
        librarianName = new javax.swing.JLabel();
        branchName = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        addMag = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        company = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        pages = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        title = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        itype = new javax.swing.JComboBox<>();
        addBook = new javax.swing.JButton();
        rejectRentalReq = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        acceptRentalReq1 = new javax.swing.JButton();
        dateAdded = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        language = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        authors = new javax.swing.JComboBox<>();
        magName = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        rentalsTable = new javax.swing.JTable();
        genreInp = new javax.swing.JTextField();
        addBook1 = new javax.swing.JButton();
        addBook2 = new javax.swing.JButton();
        authorInp = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        dateAddedMag = new com.toedter.calendar.JDateChooser();
        jLabel22 = new javax.swing.JLabel();
        bindingTypeCombo1 = new javax.swing.JComboBox<>();
        genres = new javax.swing.JComboBox<>();
        expLib = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backBtn1.setBackground(new java.awt.Color(51, 255, 255));
        backBtn1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        backBtn1.setText("Log Out");
        backBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtn1ActionPerformed(evt);
            }
        });
        jPanel1.add(backBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 30, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 0, 51));
        jLabel5.setText("Penguin Libraries");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 150, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Materials");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 80, 20));

        materialsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Material Type", "Title", "Author", "Genre", "Pages", "Company", "Issue Type", "Is Available", "Date Added"
            }
        ));
        jScrollPane2.setViewportView(materialsTable);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 820, 220));

        librarianName.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        librarianName.setText("Librarian");
        jPanel1.add(librarianName, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 130, 80, 20));

        branchName.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        branchName.setText("Branch  ");
        jPanel1.add(branchName, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 110, 80, 20));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Branch  ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 110, 70, 20));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Company");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 260, 70, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Issue Type");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 300, 70, -1));

        addMag.setBackground(new java.awt.Color(153, 255, 204));
        addMag.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        addMag.setText("Add Magazine");
        addMag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMagActionPerformed(evt);
            }
        });
        jPanel1.add(addMag, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 380, 130, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Librarian");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 130, 70, 20));

        company.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                companyActionPerformed(evt);
            }
        });
        jPanel1.add(company, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 260, 100, 30));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("Author");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, 70, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("Pages");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 220, 70, -1));

        pages.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagesActionPerformed(evt);
            }
        });
        jPanel1.add(pages, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 220, 120, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Profile");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 70, 70, 20));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setText("Title");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, 40, -1));

        title.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titleActionPerformed(evt);
            }
        });
        jPanel1.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, 120, 30));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setText("Genre");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, 70, -1));

        itype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Daily", "Weekly", "Monthly", "Yearly" }));
        jPanel1.add(itype, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 300, 100, 30));

        addBook.setBackground(new java.awt.Color(153, 255, 204));
        addBook.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        addBook.setText("Add Book");
        addBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBookActionPerformed(evt);
            }
        });
        jPanel1.add(addBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 380, 130, 30));

        rejectRentalReq.setBackground(new java.awt.Color(255, 153, 153));
        rejectRentalReq.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rejectRentalReq.setText("Reject");
        rejectRentalReq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rejectRentalReqActionPerformed(evt);
            }
        });
        jPanel1.add(rejectRentalReq, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 370, 80, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel21.setText("Rental Requests");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        acceptRentalReq1.setBackground(new java.awt.Color(153, 255, 153));
        acceptRentalReq1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        acceptRentalReq1.setText("Accept");
        acceptRentalReq1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptRentalReq1ActionPerformed(evt);
            }
        });
        jPanel1.add(acceptRentalReq1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, -1));
        jPanel1.add(dateAdded, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 340, 120, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Add Authors & Genres");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, 20));

        language.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                languageActionPerformed(evt);
            }
        });
        jPanel1.add(language, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 260, 120, 30));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setText("Language");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, 70, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setText("Date Added");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 340, 80, 20));

        jPanel1.add(authors, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, 120, 30));

        magName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                magNameActionPerformed(evt);
            }
        });
        jPanel1.add(magName, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 220, 100, 30));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel19.setText("Name");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 220, 70, -1));

        rentalsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Price", "Material ", "Duration", "Status", "Customer"
            }
        ));
        jScrollPane3.setViewportView(rentalsTable);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 370, 170));

        genreInp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genreInpActionPerformed(evt);
            }
        });
        jPanel1.add(genreInp, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 140, 30));

        addBook1.setBackground(new java.awt.Color(153, 255, 204));
        addBook1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        addBook1.setText("Add Author");
        addBook1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBook1ActionPerformed(evt);
            }
        });
        jPanel1.add(addBook1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, 30));

        addBook2.setBackground(new java.awt.Color(153, 255, 204));
        addBook2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        addBook2.setText("Add Genre");
        addBook2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBook2ActionPerformed(evt);
            }
        });
        jPanel1.add(addBook2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 100, 30));

        authorInp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                authorInpActionPerformed(evt);
            }
        });
        jPanel1.add(authorInp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 140, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Add Magazine");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 190, 110, 20));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel20.setText("Binding");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, 70, -1));
        jPanel1.add(dateAddedMag, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 340, 100, 30));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel22.setText("Date Added");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 340, 80, 20));

        bindingTypeCombo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Paper Back", "Hard Cover", "Spiral ", " " }));
        jPanel1.add(bindingTypeCombo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 300, 120, 30));

        jPanel1.add(genres, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 140, 120, 30));

        expLib.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        expLib.setText("Exp");
        jPanel1.add(expLib, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 150, 80, 20));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Exp");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 150, 70, 20));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel23.setText("Add Book");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, 70, 20));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rejectRentalReqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rejectRentalReqActionPerformed
        // TODO add your handling code here:
        int selectedRow = rentalsTable.getSelectedRow();
        String rr_id = (String) rentalsTable.getValueAt(selectedRow, 0);
        String u_id = (String) rentalsTable.getValueAt(selectedRow, 5);

        this.branch.getLibrary().rejectRentalReq(rr_id);
        this.business.rejectedReq(u_id);
        
        JOptionPane.showMessageDialog(null, "Customer Request rejected");
        populateRR();
        populateAG();
    }//GEN-LAST:event_rejectRentalReqActionPerformed

    private void addBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBookActionPerformed
        // TODO add your handling code here:
        String titleBook = title.getText();
        Date dateBook = dateAdded.getDate();
        String authorBook = (String) authors.getSelectedItem();
        String genreBook = (String) genres.getSelectedItem();
        String pagesBook = pages.getText();
        String langBook = language.getText();
        String typeOfBindingBook = (String) authors.getSelectedItem();

        //create author and genre, add them to respective directory, and return the author or genre
        branch.getLibrary().addToAuthorDirectory(authorBook);
        branch.getLibrary().addToGenreDirectory(genreBook);
        branch.getLibrary().getBookDirectory().addBook(titleBook, dateBook, authorBook, 
                genreBook, pagesBook, langBook, typeOfBindingBook, this.branch.getName());
        JOptionPane.showMessageDialog(null, "Book added");
        populateMaterial();
        
    }//GEN-LAST:event_addBookActionPerformed

    private void titleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_titleActionPerformed

    private void pagesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pagesActionPerformed

    private void companyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_companyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_companyActionPerformed

    private void addMagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMagActionPerformed
        // TODO add your handling code here:
        String companyMag = company.getText();
        String issueMag = (String) itype.getSelectedItem();
        String magname = magName.getText();
        Date dateBook = dateAddedMag.getDate();
        
        //create author and genre, add them to respective directory, and return the author or genre
        branch.getLibrary().getMagDiretory().addMagazine(magname, dateBook,companyMag, issueMag, this.branch.getName());
        JOptionPane.showMessageDialog(null, "Magazine added");
        populateMaterial();
    }//GEN-LAST:event_addMagActionPerformed

    private void backBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtn1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new MainJFrame(business, branch, useraccount);
    }//GEN-LAST:event_backBtn1ActionPerformed

    private void acceptRentalReq1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptRentalReq1ActionPerformed
        // TODO add your handling code here:
        int selectedRow = rentalsTable.getSelectedRow();
        String rr_id = (String) rentalsTable.getValueAt(selectedRow, 0);
        String u_id = (String) rentalsTable.getValueAt(selectedRow, 5);
        this.branch.getLibrary().acceptRentalReq(rr_id);
        this.business.acceptedReq(u_id);
        JOptionPane.showMessageDialog(null, "Customer Request accepted");
        populateRR();
        populateMaterial();
    }//GEN-LAST:event_acceptRentalReq1ActionPerformed

    private void languageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_languageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_languageActionPerformed

    private void magNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_magNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_magNameActionPerformed

    private void genreInpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genreInpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genreInpActionPerformed

    private void addBook1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBook1ActionPerformed
        // TODO add your handling code here:
        this.branch.getLibrary().addToAuthorDirectory(authorInp.getText());
        populateAG();
    }//GEN-LAST:event_addBook1ActionPerformed

    private void addBook2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBook2ActionPerformed
        // TODO add your handling code here:
        this.branch.getLibrary().addToGenreDirectory(genreInp.getText());
        populateAG();
    }//GEN-LAST:event_addBook2ActionPerformed

    private void authorInpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_authorInpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_authorInpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LibrarianJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LibrarianJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LibrarianJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LibrarianJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new SystemAdminJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceptRentalReq1;
    private javax.swing.JButton addBook;
    private javax.swing.JButton addBook1;
    private javax.swing.JButton addBook2;
    private javax.swing.JButton addMag;
    private javax.swing.JTextField authorInp;
    private javax.swing.JComboBox<String> authors;
    private javax.swing.JButton backBtn1;
    private javax.swing.JComboBox<String> bindingTypeCombo1;
    private javax.swing.JLabel branchName;
    private javax.swing.JTextField company;
    private com.toedter.calendar.JDateChooser dateAdded;
    private com.toedter.calendar.JDateChooser dateAddedMag;
    private javax.swing.JLabel expLib;
    private javax.swing.JTextField genreInp;
    private javax.swing.JComboBox<String> genres;
    private javax.swing.JComboBox<String> itype;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField language;
    private javax.swing.JLabel librarianName;
    private javax.swing.JTextField magName;
    private javax.swing.JTable materialsTable;
    private javax.swing.JTextField pages;
    private javax.swing.JButton rejectRentalReq;
    private javax.swing.JTable rentalsTable;
    private javax.swing.JTextField title;
    // End of variables declaration//GEN-END:variables
}
