/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.Chef;
import Model.CookBook;
import Model.Recipe;
import javax.swing.JOptionPane;

/**
 *
 * @author 15512
 */
public class AddRecipe extends javax.swing.JPanel {

    /**
     * Creates new form AddRecipePanel
     */
    private CookBook cookBook;

    public AddRecipe(CookBook cookBook) {
        initComponents();
        this.cookBook = cookBook;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        recipeName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        category = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        servingSize = new javax.swing.JTextField();
        difficultyLevel = new javax.swing.JSlider();
        jLabel11 = new javax.swing.JLabel();
        recipeImage = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        desc = new javax.swing.JTextArea();
        glutenFree = new javax.swing.JCheckBox();
        jLabel12 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        numItems = new javax.swing.JTextField();
        chefEmail = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        chefln = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        cheffn = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        chefPhone = new javax.swing.JTextField();
        chefUsername = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        addRecipeButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 51, 51));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        recipeName.setBackground(new java.awt.Color(51, 51, 51));
        recipeName.setForeground(new java.awt.Color(255, 255, 255));
        recipeName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        recipeName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recipeNameActionPerformed(evt);
            }
        });
        add(recipeName, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 149, -1));

        jLabel5.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Recipe Name");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 25, -1, -1));

        category.setBackground(new java.awt.Color(51, 51, 51));
        category.setForeground(new java.awt.Color(255, 255, 255));
        category.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        add(category, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 149, -1));

        jLabel10.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Description :");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 110, 87, -1));

        jLabel6.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Serving Size");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 49, -1, -1));

        servingSize.setBackground(new java.awt.Color(51, 51, 51));
        servingSize.setForeground(new java.awt.Color(255, 255, 255));
        servingSize.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        add(servingSize, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 149, -1));
        add(difficultyLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 110, -1));

        jLabel11.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Difficulty");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 62, -1));

        recipeImage.setBackground(new java.awt.Color(51, 51, 51));
        recipeImage.setForeground(new java.awt.Color(255, 255, 255));
        recipeImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        add(recipeImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, 111, -1));

        desc.setBackground(new java.awt.Color(51, 51, 51));
        desc.setColumns(20);
        desc.setForeground(new java.awt.Color(255, 255, 255));
        desc.setRows(5);
        desc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        jScrollPane1.setViewportView(desc);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 134, 276, 160));

        glutenFree.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        glutenFree.setForeground(new java.awt.Color(255, 255, 255));
        glutenFree.setText("Gluten Free");
        glutenFree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                glutenFreeActionPerformed(evt);
            }
        });
        add(glutenFree, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, -1, -1));

        jLabel12.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Recipe Image at ");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, -1, -1));

        jLabel8.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("No. of Ingredients");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, -1, -1));

        jLabel9.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Category");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 73, -1, -1));

        numItems.setBackground(new java.awt.Color(51, 51, 51));
        numItems.setForeground(new java.awt.Color(255, 255, 255));
        numItems.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        add(numItems, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, 36, -1));

        chefEmail.setBackground(new java.awt.Color(51, 51, 51));
        chefEmail.setForeground(new java.awt.Color(255, 255, 255));
        chefEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        add(chefEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 200, 149, -1));

        jLabel14.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Email");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, -1, -1));

        chefln.setBackground(new java.awt.Color(51, 51, 51));
        chefln.setForeground(new java.awt.Color(255, 255, 255));
        chefln.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        add(chefln, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, 149, -1));

        jLabel7.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Last name");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, -1, -1));

        jLabel15.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("First name");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, -1, -1));

        cheffn.setBackground(new java.awt.Color(51, 51, 51));
        cheffn.setForeground(new java.awt.Color(255, 255, 255));
        cheffn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        cheffn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cheffnActionPerformed(evt);
            }
        });
        add(cheffn, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, 149, -1));

        jLabel16.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 204, 255));
        jLabel16.setText("Chef's Details");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, 131, -1));

        jLabel17.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Phone");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, -1, -1));

        chefPhone.setBackground(new java.awt.Color(51, 51, 51));
        chefPhone.setForeground(new java.awt.Color(255, 255, 255));
        chefPhone.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        add(chefPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, 149, -1));

        chefUsername.setBackground(new java.awt.Color(51, 51, 51));
        chefUsername.setForeground(new java.awt.Color(255, 255, 255));
        chefUsername.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        add(chefUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, 149, -1));

        jLabel18.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Username");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, -1, -1));

        addRecipeButton1.setBackground(new java.awt.Color(204, 255, 204));
        addRecipeButton1.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        addRecipeButton1.setForeground(new java.awt.Color(51, 51, 51));
        addRecipeButton1.setText("Add Recipe");
        addRecipeButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addRecipeButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRecipeButton1ActionPerformed(evt);
            }
        });
        add(addRecipeButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, 100, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void recipeNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recipeNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_recipeNameActionPerformed

    private void glutenFreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_glutenFreeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_glutenFreeActionPerformed

    private void cheffnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cheffnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cheffnActionPerformed

    private void addRecipeButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRecipeButton1ActionPerformed
        // TODO add your handling code here:
        if (category.getText().trim().length() == 0
                || desc.getText().trim().length() == 0
                || recipeImage.getText().trim().length() == 0
                || difficultyLevel.getValue() == 0
                || numItems.getText().trim().length() == 0
                || recipeName.getText().trim().length() == 0
                || servingSize.getText().trim().length() == 0
                || chefEmail.getText().trim().length() == 0
                || cheffn.getText().trim().length() == 0
                || chefln.getText().trim().length() == 0
                || chefPhone.getText().trim().length() == 0
                || chefUsername.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Empty values are not accepted.");
        }

        Recipe recipe = new Recipe();
        Chef chefDetails = new Chef();
        recipe.setCategory(category.getText());
        recipe.setDescription(desc.getText());
        recipe.setDifficulty(Double.parseDouble(String.valueOf(difficultyLevel.getValue())));
        recipe.setGlutenFree(glutenFree.isSelected());
        recipe.setNumOfItems(Integer.valueOf(numItems.getText()));
        recipe.setRecipeImage(recipeImage.getText());
        recipe.setRecipeName(recipeName.getText());
        recipe.setServingSize(Integer.valueOf(servingSize.getText()));

        chefDetails.setEmail(chefEmail.getText());
        chefDetails.setFirstName(cheffn.getText());
        chefDetails.setLastName(chefln.getText());
        chefDetails.setPhone(chefPhone.getText());
        chefDetails.setUsername(chefUsername.getText());

        recipe.setChefDetails(chefDetails);

        this.cookBook.addToRecipeDB(recipe);
        JOptionPane.showMessageDialog(null, "Added Recipe");
//        new Home(this.cookBook);
    }//GEN-LAST:event_addRecipeButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addRecipeButton1;
    private javax.swing.JTextField category;
    private javax.swing.JTextField chefEmail;
    private javax.swing.JTextField chefPhone;
    private javax.swing.JTextField chefUsername;
    private javax.swing.JTextField cheffn;
    private javax.swing.JTextField chefln;
    private javax.swing.JTextArea desc;
    private javax.swing.JSlider difficultyLevel;
    private javax.swing.JCheckBox glutenFree;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField numItems;
    private javax.swing.JTextField recipeImage;
    private javax.swing.JTextField recipeName;
    private javax.swing.JTextField servingSize;
    // End of variables declaration//GEN-END:variables
}
