/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import Model.CookBook;
import Model.Recipe;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JList;

/**
 *
 * @author 15512
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Recipe recipe;
//    public Home(Recipe rec) {
//        recipe = rec;
//        initComponents();
////        refreshList();
//    }
//    
    public Home() {
        recipe = new Recipe();
        initComponents();
//        refreshList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        phone = new javax.swing.JLabel();
        usename = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        numItems = new javax.swing.JLabel();
        imagePath = new javax.swing.JLabel();
        category = new javax.swing.JLabel();
        servingSizee = new javax.swing.JLabel();
        recipeTitleMain = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        difficultyLevel = new javax.swing.JProgressBar();
        glutenFree = new javax.swing.JCheckBox();
        description = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        viewRecipeList1 = new javax.swing.JButton();
        menuButton = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        dateAdded1 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        addRecipeButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        viewButton = new javax.swing.JButton();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setBackground(new java.awt.Color(204, 204, 255));
        jLabel1.setFont(new java.awt.Font("Rockwell", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("CookBook");

        jLabel4.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Your Recipe logger");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(284, 284, 284)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(310, 310, 310)
                        .addComponent(jLabel4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 204, 255));
        jLabel15.setText("Actions :");
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 260, -1, -1));

        jLabel20.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Name");
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 113, 61, -1));

        jLabel17.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Email");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 133, -1, -1));

        jLabel14.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Username");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 153, -1, -1));

        jLabel16.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Phone");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 173, -1, -1));

        phone.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        phone.setForeground(new java.awt.Color(255, 255, 255));
        phone.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        jPanel4.add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 173, 113, 18));

        usename.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        usename.setForeground(new java.awt.Color(255, 255, 255));
        usename.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        jPanel4.add(usename, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 153, 113, 18));

        email.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        email.setForeground(new java.awt.Color(255, 255, 255));
        email.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        jPanel4.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 133, 113, 18));

        name.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 255));
        name.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        jPanel4.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 113, 113, 18));

        jLabel6.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Serving Size");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 91, -1, -1));

        jLabel9.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Category");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 113, -1, -1));

        jLabel12.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Recipe Image at ");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 139, -1, -1));

        jLabel10.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("No. of Ingredients");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 163, -1, -1));

        numItems.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        numItems.setForeground(new java.awt.Color(255, 255, 255));
        numItems.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        jPanel4.add(numItems, new org.netbeans.lib.awtextra.AbsoluteConstraints(464, 163, 60, 18));

        imagePath.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        imagePath.setForeground(new java.awt.Color(255, 255, 255));
        imagePath.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        jPanel4.add(imagePath, new org.netbeans.lib.awtextra.AbsoluteConstraints(464, 139, 161, 18));

        category.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        category.setForeground(new java.awt.Color(255, 255, 255));
        category.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        jPanel4.add(category, new org.netbeans.lib.awtextra.AbsoluteConstraints(464, 115, 113, 18));

        servingSizee.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        servingSizee.setForeground(new java.awt.Color(255, 255, 255));
        servingSizee.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        jPanel4.add(servingSizee, new org.netbeans.lib.awtextra.AbsoluteConstraints(464, 91, 58, 18));

        recipeTitleMain.setFont(new java.awt.Font("Rockwell", 3, 24)); // NOI18N
        recipeTitleMain.setForeground(new java.awt.Color(255, 255, 255));
        recipeTitleMain.setText("Recipe Title");
        jPanel4.add(recipeTitleMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 162, 33));

        jLabel11.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Difficulty");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 193, 62, -1));

        difficultyLevel.setForeground(new java.awt.Color(204, 204, 255));
        difficultyLevel.setValue(25);
        jPanel4.add(difficultyLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(468, 193, 160, 20));

        glutenFree.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        glutenFree.setForeground(new java.awt.Color(255, 255, 255));
        glutenFree.setSelected(true);
        glutenFree.setText("Gluten Free");
        glutenFree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                glutenFreeActionPerformed(evt);
            }
        });
        jPanel4.add(glutenFree, new org.netbeans.lib.awtextra.AbsoluteConstraints(464, 235, -1, -1));

        description.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        description.setForeground(new java.awt.Color(255, 255, 255));
        description.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        jPanel4.add(description, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 252, 450, 164));

        jLabel13.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 255));
        jLabel13.setText("Description :");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(474, 57, 120, -1));

        viewRecipeList1.setBackground(new java.awt.Color(51, 51, 51));
        viewRecipeList1.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        viewRecipeList1.setForeground(new java.awt.Color(204, 255, 204));
        viewRecipeList1.setText("Update Recipe");
        viewRecipeList1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        viewRecipeList1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewRecipeList1ActionPerformed(evt);
            }
        });
        jPanel4.add(viewRecipeList1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 300, 122, -1));

        menuButton.setBackground(new java.awt.Color(51, 51, 51));
        menuButton.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        menuButton.setForeground(new java.awt.Color(255, 102, 102));
        menuButton.setText("Delete Recipe");
        menuButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        menuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuButtonActionPerformed(evt);
            }
        });
        jPanel4.add(menuButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 340, 120, 30));

        jLabel21.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(204, 204, 255));
        jLabel21.setText("Chef's Details :");
        jPanel4.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 79, -1, -1));

        jLabel22.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(204, 204, 255));
        jLabel22.setText("Description :");
        jPanel4.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 224, 120, -1));

        dateAdded1.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        dateAdded1.setForeground(new java.awt.Color(204, 204, 255));
        dateAdded1.setText("29th Jan 2023");
        jPanel4.add(dateAdded1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 162, 33));

        jSplitPane1.setRightComponent(jPanel4);

        jPanel7.setBackground(new java.awt.Color(51, 51, 51));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addRecipeButton.setBackground(new java.awt.Color(51, 51, 51));
        addRecipeButton.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        addRecipeButton.setForeground(new java.awt.Color(204, 204, 255));
        addRecipeButton.setText("Add Recipe");
        addRecipeButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addRecipeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRecipeButtonActionPerformed(evt);
            }
        });
        jPanel7.add(addRecipeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 90, 30));

        updateButton.setBackground(new java.awt.Color(51, 51, 51));
        updateButton.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        updateButton.setForeground(new java.awt.Color(204, 204, 255));
        updateButton.setText("Update  Recipe");
        updateButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });
        jPanel7.add(updateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 120, 30));

        viewButton.setBackground(new java.awt.Color(51, 51, 51));
        viewButton.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        viewButton.setForeground(new java.awt.Color(204, 204, 255));
        viewButton.setText("View  Recipe");
        viewButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        viewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewButtonActionPerformed(evt);
            }
        });
        jPanel7.add(viewButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 110, 30));

        jSplitPane1.setLeftComponent(jPanel7);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 816, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void addRecipeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRecipeButtonActionPerformed
        // TODO add your handling code here:
        jSplitPane1.setRightComponent(new AddRecipe(recipe));
        
    }//GEN-LAST:event_addRecipeButtonActionPerformed
    
    private void menuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuButtonActionPerformed

    private void viewRecipeList1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewRecipeList1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewRecipeList1ActionPerformed

    private void glutenFreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_glutenFreeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_glutenFreeActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
        Update update = new Update(this.recipe);
        jSplitPane1.setRightComponent(update);
    }//GEN-LAST:event_updateButtonActionPerformed

    private void viewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewButtonActionPerformed
        // TODO add your handling code here:
        ViewMain viewPanel = new ViewMain(this.recipe);
        jSplitPane1.setRightComponent(viewPanel);
    }//GEN-LAST:event_viewButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addRecipeButton;
    private javax.swing.JLabel category;
    private javax.swing.JLabel dateAdded1;
    private javax.swing.JLabel description;
    private javax.swing.JProgressBar difficultyLevel;
    private javax.swing.JLabel email;
    private javax.swing.JCheckBox glutenFree;
    private javax.swing.JLabel imagePath;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton menuButton;
    private javax.swing.JLabel name;
    private javax.swing.JLabel numItems;
    private javax.swing.JLabel phone;
    private javax.swing.JLabel recipeTitleMain;
    private javax.swing.JLabel servingSizee;
    private javax.swing.JButton updateButton;
    private javax.swing.JLabel usename;
    private javax.swing.JButton viewButton;
    private javax.swing.JButton viewRecipeList1;
    // End of variables declaration//GEN-END:variables
}
