/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.Business;
import Model.InsurancePlan;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author forumkaria
 */

public
        class ViewInsurancePlans extends javax.swing.JPanel {

    /**
     * Creates new form ViewInsPlanJPanel
     */
    Business business;
    InsurancePlan selectedInsurancePlan;
    DefaultTableModel viewTableModel;
     
    
    public
            ViewInsurancePlans(Business b) {
        initComponents();
        
        this.business = b;
        this.viewTableModel = (DefaultTableModel) InsurPlanJTable.getModel();
        
        display();
        
    }

     public void display(){
         ArrayList<InsurancePlan> insuranceDirectory = this.business.getInsurancePlansDirectory();

        if (insuranceDirectory.size() > 0) {
            // display

            viewTableModel.setRowCount(0);
            
            for (InsurancePlan ip : insuranceDirectory) {
                // number of columns in the table = 3 and row should be framed
                Object row[] = new Object[5];
                row[0] = ip.getPlanId();
                row[1] = ip.getPlanName();
                row[2] = ip.getCostPerMonth();
                row[3] = ip.getCostPerYear();
                // add the row to the table
                viewTableModel.addRow(row);
            }
        } else {
            System.out.print("Empty list");
        }
    }

           
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        InsurancePlanUpdateHeader = new javax.swing.JLabel();
        planIDJLabel = new javax.swing.JLabel();
        InsPlanIDTxtField = new javax.swing.JTextField();
        planNameJLabel = new javax.swing.JLabel();
        InsPlanNameTxtField = new javax.swing.JTextField();
        planMonthCostJLabel = new javax.swing.JLabel();
        planAnnualCostJLabel = new javax.swing.JLabel();
        InsPlanAnnualCostTxtField = new javax.swing.JTextField();
        InsPlanMonCostTxtField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        InsurPlanJTable = new javax.swing.JTable();
        ViewInsDetailsBtn = new javax.swing.JButton();
        deleteVaccination = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));

        InsurancePlanUpdateHeader.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        InsurancePlanUpdateHeader.setText("INSURANCE PLAN DETAILS");

        planIDJLabel.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        planIDJLabel.setText("Plan ID:");

        InsPlanIDTxtField.setEditable(false);
        InsPlanIDTxtField.setEnabled(false);

        planNameJLabel.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        planNameJLabel.setText("Plan Name:");

        InsPlanNameTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsPlanNameTxtFieldActionPerformed(evt);
            }
        });

        planMonthCostJLabel.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        planMonthCostJLabel.setText("Plan Monthly Cost:");

        planAnnualCostJLabel.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        planAnnualCostJLabel.setText("Plan Annual Cost:");

        InsPlanAnnualCostTxtField.setEditable(false);
        InsPlanAnnualCostTxtField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                InsPlanAnnualCostTxtFieldFocusLost(evt);
            }
        });

        InsPlanMonCostTxtField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                InsPlanMonCostTxtFieldFocusLost(evt);
            }
        });

        InsurPlanJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Plan ID", "Plan Name", "Monthly Cost", "Annual Cost"
            }
        ));
        jScrollPane1.setViewportView(InsurPlanJTable);

        ViewInsDetailsBtn.setBackground(new java.awt.Color(51, 204, 0));
        ViewInsDetailsBtn.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        ViewInsDetailsBtn.setText("VIEW DETAILS");
        ViewInsDetailsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewInsDetailsBtnActionPerformed(evt);
            }
        });

        deleteVaccination.setBackground(new java.awt.Color(255, 153, 153));
        deleteVaccination.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        deleteVaccination.setText("Delete");
        deleteVaccination.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteVaccinationActionPerformed(evt);
            }
        });

        updateBtn.setBackground(new java.awt.Color(51, 204, 0));
        updateBtn.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(planIDJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(66, 66, 66)
                                .addComponent(InsPlanIDTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(planAnnualCostJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(InsPlanAnnualCostTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(planNameJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(planMonthCostJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(1, 1, 1)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(InsPlanMonCostTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(InsPlanNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(269, 269, 269)
                        .addComponent(InsurancePlanUpdateHeader)))
                .addContainerGap(126, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(deleteVaccination, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ViewInsDetailsBtn)
                .addGap(279, 279, 279))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(120, 120, 120)
                    .addComponent(updateBtn)
                    .addContainerGap(673, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(InsurancePlanUpdateHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(planIDJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(InsPlanIDTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(planNameJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(InsPlanNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(planMonthCostJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(InsPlanMonCostTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(planAnnualCostJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(InsPlanAnnualCostTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(ViewInsDetailsBtn)
                        .addContainerGap(135, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(deleteVaccination)
                        .addGap(145, 145, 145))))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(332, Short.MAX_VALUE)
                    .addComponent(updateBtn)
                    .addGap(213, 213, 213)))
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void ViewInsDetailsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewInsDetailsBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = InsurPlanJTable.getSelectedRow();
        
        if(selectedRow >= 0){
            
            InsPlanIDTxtField.setText(String.valueOf(viewTableModel.getValueAt(selectedRow,0)));
            InsPlanNameTxtField.setText(String.valueOf( viewTableModel.getValueAt(selectedRow,1)));
            InsPlanMonCostTxtField.setText(String.valueOf( viewTableModel.getValueAt(selectedRow,2)));
            InsPlanAnnualCostTxtField.setText(String.valueOf( viewTableModel.getValueAt(selectedRow,3)));
            
        } else{
            // NO SELECTION MADE BY USER
            JOptionPane.showMessageDialog(null, "Please select row");
        }
        
    }//GEN-LAST:event_ViewInsDetailsBtnActionPerformed

    private void deleteVaccinationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteVaccinationActionPerformed
        // TODO add your handling code here:
        int selectedRow = InsurPlanJTable.getSelectedRow();
        
        this.business.deleteIpById(Integer.valueOf(InsPlanIDTxtField.getText()));
        display();

    }//GEN-LAST:event_deleteVaccinationActionPerformed

    private void InsPlanNameTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsPlanNameTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InsPlanNameTxtFieldActionPerformed

    private void InsPlanAnnualCostTxtFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_InsPlanAnnualCostTxtFieldFocusLost
        // TODO add your handling code here:
        
//         InsPlanAnnualCostTxtField.setText(String.valueOf(Float.parseFloat (InsPlanMonCostTxtField.getText())*12));
    }//GEN-LAST:event_InsPlanAnnualCostTxtFieldFocusLost

    private void InsPlanMonCostTxtFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_InsPlanMonCostTxtFieldFocusLost
        // TODO add your handling code here:
        
        InsPlanAnnualCostTxtField.setText(String.valueOf(Float.parseFloat (InsPlanMonCostTxtField.getText())*12));
    }//GEN-LAST:event_InsPlanMonCostTxtFieldFocusLost

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = InsurPlanJTable.getSelectedRow();
        
        this.business.findIpById((int)viewTableModel.getValueAt(selectedRow,0)).setPlanName(InsPlanNameTxtField.getText());
        
        this.business.findIpById((int)viewTableModel.getValueAt(selectedRow,0)).setCostPerMonth(Float.valueOf(InsPlanMonCostTxtField.getText()));
        
        this.business.findIpById((int)viewTableModel.getValueAt(selectedRow,0)).setCostPerYear(Float.valueOf(InsPlanAnnualCostTxtField.getText()));
         
        display();
    }//GEN-LAST:event_updateBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField InsPlanAnnualCostTxtField;
    private javax.swing.JTextField InsPlanIDTxtField;
    private javax.swing.JTextField InsPlanMonCostTxtField;
    private javax.swing.JTextField InsPlanNameTxtField;
    private javax.swing.JTable InsurPlanJTable;
    private javax.swing.JLabel InsurancePlanUpdateHeader;
    private javax.swing.JButton ViewInsDetailsBtn;
    private javax.swing.JButton deleteVaccination;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel planAnnualCostJLabel;
    private javax.swing.JLabel planIDJLabel;
    private javax.swing.JLabel planMonthCostJLabel;
    private javax.swing.JLabel planNameJLabel;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
