/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.SystemAdminPanels;

import Business.Branch;
import Business.Business;
import Role.BranchAdminRole;
import Role.CustomerRole;
import Role.LibrarianRole;
import Role.Role;
import UI.MainJFrame;
import UserAccount.UserAccount;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 15512
 */
public class SystemAdminJFrame extends javax.swing.JFrame {

    private Business business;
    private Branch branch;
    private UserAccount useraccount;
    DefaultTableModel branchTable;
    DefaultTableModel userTable;

    /**
     * Creates new form SystemAdminJFrame
     */
    public SystemAdminJFrame(Business business, Branch branch, UserAccount useraccount) {
        initComponents();
        this.setVisible(true);
//s
        this.business = business;
        this.useraccount = useraccount;
        this.branchTable = (DefaultTableModel) branchesTable.getModel();
        this.userTable = (DefaultTableModel) usersTable.getModel();
        populateDropdown();
        populateBranches();
        populateUsers();
    }

    public void populateDropdown() {
        jComboBox1.removeAllItems();
        for (String rolename : Role.getAllRoles()) {
            jComboBox1.addItem(rolename);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buildingNum = new javax.swing.JTextField();
        username = new javax.swing.JTextField();
        registerBtn = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        password = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        backBtn1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        branchesTable = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        usersTable = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        addBranchBtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        deleteBranch = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        exp = new javax.swing.JTextField();
        branchName = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        fieldBranch = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(buildingNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 440, 120, 30));
        jPanel1.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, 170, 30));

        registerBtn.setBackground(new java.awt.Color(153, 255, 204));
        registerBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        registerBtn.setText("Register");
        registerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBtnActionPerformed(evt);
            }
        });
        jPanel1.add(registerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 540, -1, 30));

        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 540, 100, 30));
        jPanel1.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 420, 170, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 0, 51));
        jLabel4.setText("Branches");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 150, 30));

        backBtn1.setBackground(new java.awt.Color(51, 255, 255));
        backBtn1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        backBtn1.setText("Log Out");
        backBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtn1ActionPerformed(evt);
            }
        });
        jPanel1.add(backBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 30, -1, -1));

        branchesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "Location", "Librarian", "Manager"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(branchesTable);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 360, 160));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 0, 51));
        jLabel5.setText("Penguin Libraries");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 150, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Username");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 70, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Building No");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 420, 100, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Role");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, 40, -1));

        usersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Account ID", "Username", "Role"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(usersTable);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 320, 160));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 0, 51));
        jLabel7.setText("Branch Actions");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 340, 170, 30));

        jButton2.setBackground(new java.awt.Color(153, 255, 204));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setText("Select Branch");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, 110, -1));

        addBranchBtn.setBackground(new java.awt.Color(153, 255, 204));
        addBranchBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        addBranchBtn.setText("Add Branch");
        addBranchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBranchBtnActionPerformed(evt);
            }
        });
        jPanel1.add(addBranchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 440, -1, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 0, 51));
        jLabel8.setText("User Accounts");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 150, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 0, 51));
        jLabel9.setText("Register Accounts");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 170, 30));

        deleteBranch.setBackground(new java.awt.Color(255, 153, 153));
        deleteBranch.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        deleteBranch.setText("Delete Branch");
        deleteBranch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBranchActionPerformed(evt);
            }
        });
        jPanel1.add(deleteBranch, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 300, 110, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Name");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 70, -1));
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 460, 170, 30));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Experience (If employee)");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 160, 30));
        jPanel1.add(exp, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 500, 70, 30));
        jPanel1.add(branchName, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 390, 120, 30));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Password");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 70, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("Branch Name");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 370, 100, -1));

        fieldBranch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel1.add(fieldBranch, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 590, 120, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Branch Selected : ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 590, 130, 20));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deleteBranchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBranchActionPerformed
        // TODO add your handling code here:
        String bName = fieldBranch.getText();
        if (bName != "") {
            this.business.deleteBranch(bName);
            populateBranches();
        } else {
            JOptionPane.showMessageDialog(null, "Select Branch");
        }

    }//GEN-LAST:event_deleteBranchActionPerformed

    private void addBranchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBranchBtnActionPerformed
        // TODO add your handling code here:
        this.business.createBranch(branchName.getText(), buildingNum.getText());
        populateBranches();
    }//GEN-LAST:event_addBranchBtnActionPerformed
    private void populateBranches() {
        branchTable.setRowCount(0);

        ArrayList<Branch> branches = this.business.getBranches();

        if (branches.size() > 0) {
            for (Branch br : branches) {
                Object[] row = new Object[4];
                row[0] = br.getName();
                row[1] = br.getLibrary().getLib_building();
                row[2] = br.getLibrary().getLibrarian() == null ? "N/A" : br.getLibrary().getLibrarian().getEmp_name();
                row[3] = br.getLibrary().getManager() == null ? "N/A" : br.getLibrary().getManager().getEmp_name();
                branchTable.addRow(row);
            }
        }
    }

    private void populateUsers() {
        userTable.setRowCount(0);

        ArrayList<UserAccount> uas = this.business.getUserAccounts().getUseraccountList();
        ArrayList<Branch> branches = this.business.getBranches();
        if (uas.size() > 0) {
            for (UserAccount ua : uas) {
                Object[] row = new Object[3];
                row[0] = ua.getAccountId();
                row[1] = ua.getUsername();
                row[2] = ua.getRole();
                userTable.addRow(row);
            }

            for (Branch br : branches) {
                ArrayList<UserAccount> uasb = br.getBranchUad().getUseraccountList();
                for (UserAccount ua : uasb) {
                    Object[] row = new Object[3];
                    row[0] = ua.getAccountId();
                    row[1] = ua.getUsername();
                    row[2] = ua.getRole();
                    userTable.addRow(row);
                }
            }
        }
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int selectedRow = branchesTable.getSelectedRow();
        String br_name = (String) branchesTable.getValueAt(selectedRow, 0);
        this.branch = this.business.findBranchByName(br_name);
        fieldBranch.setText(this.branch.getName());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void backBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtn1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new MainJFrame(business, branch, useraccount);
    }//GEN-LAST:event_backBtn1ActionPerformed

    private void registerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBtnActionPerformed
        // TODO add your handling code here:

        // based on role selected, we will register the person into those directories
        // remember to check if the credentials are unique
        if (jComboBox1.getSelectedItem().equals("customer")) {
            UserAccount customer = this.business.getUserAccounts().createUserAccount(username.getText(), password.getText(), new CustomerRole());
            if (customer == null) {
                JOptionPane.showMessageDialog(null, "Username already exists");
            } else {
                this.business.addCustomer(customer.getAccountId(), name.getText());
                JOptionPane.showMessageDialog(null, "Added Customer");
                populateUsers();
            }
        }

        if (jComboBox1.getSelectedItem().equals("manager")) {
            String bName = fieldBranch.getText();
            if (bName != "") {
                UserAccount emp = this.branch.getBranchUad().createUserAccount(username.getText(), password.getText(), new BranchAdminRole());
                if (emp == null) {
                    JOptionPane.showMessageDialog(null, "Username already exists");
                } else {
                    this.business.findBranchByName(bName).getLibrary().addEmployee(emp.getAccountId(), name.getText(), "manager",
                            Integer.parseInt(exp.getText()), this.branch.getLibrary());
                    JOptionPane.showMessageDialog(null, "Added Branch manager");
                    populateUsers();
                    populateBranches();
                }
            } else {
                JOptionPane.showMessageDialog(null, "Create a new branch by filling the branch field to add it's branch manager.");
            }
        }
        if (jComboBox1.getSelectedItem().equals("librarian")) {
            String bName = fieldBranch.getText();
            if (bName != "") {
                UserAccount emp = this.branch.getBranchUad().createUserAccount(username.getText(), password.getText(), new LibrarianRole());
                if (emp == null) {
                    JOptionPane.showMessageDialog(null, "Username already exists");
                } else {
                    this.business.findBranchByName(bName).getLibrary().addEmployee(emp.getAccountId(), name.getText(), "librarian",
                            Integer.parseInt(exp.getText()), this.branch.getLibrary());
                    JOptionPane.showMessageDialog(null, "Added Librarian");
                    populateUsers();
                    populateBranches();
                }
            } else {
                JOptionPane.showMessageDialog(null, "Create a new branch by filling the branch field to add it's librarian.");
            }
        }
    }//GEN-LAST:event_registerBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SystemAdminJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SystemAdminJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SystemAdminJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SystemAdminJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new SystemAdminJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBranchBtn;
    private javax.swing.JButton backBtn1;
    private javax.swing.JTextField branchName;
    private javax.swing.JTable branchesTable;
    private javax.swing.JTextField buildingNum;
    private javax.swing.JButton deleteBranch;
    private javax.swing.JTextField exp;
    private javax.swing.JLabel fieldBranch;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField name;
    private javax.swing.JTextField password;
    private javax.swing.JButton registerBtn;
    private javax.swing.JTextField username;
    private javax.swing.JTable usersTable;
    // End of variables declaration//GEN-END:variables
}
